//
//  MapModels.swift
//  Virtual Tourist
//
//  Created by Eric Pedersen on 1/10/19.
//  Copyright (c) 2019 Eric Pedersen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Map
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
